apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
spec:
  containers:
    - name: pod-secrets
      image: alpine/curl
      args:
        - sleep
        - infinity
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: simple-secrets
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: simple-secrets
              key: password